### ISSUE TITLE
Error building latest 2.5.0-snapshot - en_AU != en_US

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#111]
...
griffon.core.editors.LocalePropertyEditorSpec > Locale literal '' should be equal to en_AU FAILED
    org.spockframework.runtime.SpockComparisonFailure at LocalePropertyEditorSpec.groovy:34
Test results griffon-core: FAILURE (1554 tests, 1553 passed, 1 failed, 0 skipped)

1554 tests completed, 1 failed
:griffon-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':griffon-core:test'.
> There were failing tests. See the report at: file:///C:/dev/git_local/griffon/subprojects/griffon-core/build/reports/tests/index.h
tml

----------

Condition not satisfied:

value == editor.value
|     |  |      |
en_AU |  |      en_US
      |  griffon.core.editors.LocalePropertyEditor@416b08e3
      false

	at griffon.core.editors.LocalePropertyEditorSpec.Locale literal '#literal' should be equal to #value(LocalePropertyEditorSpec.groovy:34)

**Comment by aalmiray** [comment]
Could you do me a favor an substitute `Locale.US` for `Locale.ENGLISH` and test again? Hopefully a less specific locale will work this time.

**Comment by shnplr** [comment]
Hi, which file do I need to substitute the Locale?

**Comment by shnplr** [comment]
Ah. OK the offending line is:

https://github.com/griffon/griffon/blob/0a5016083d28bb3ca974c0f4a1d577926fe25dba/subprojects/griffon-core/src/test/groovy/griffon/core/editors/LocalePropertyEditorSpec.groovy#L39

It appears on my machine that
1. '' resolves to 'en_US'
2. Locale.default resolves to 'en_AU'

Locale.ENGLISH fails ('en' != 'en_US')

**Comment by aalmiray** [comment]
Interesting conundrum given that `LocalePropertyEditor` relies on `LocaleFormatter` to parse a literal input. `LocaleFormatter` uses `GriffonAppliationUtils.parseLocale` in turn https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/griffon/util/GriffonApplicationUtils.java#L568

As you can see, `Locale.default` is returned if the literal is blank. I have no idea why you're getting 'en_US' instead of 'en_AU'. Perhaps it could be a side effect of another test that modifies `Locale.default`? If so, running this particular test in isolation should result in a green bar. If that's the case we'll know for sure another test has changed a JVM wide setting such as `Locale.default`.

**Comment by aalmiray** [comment]
Got it. The base spec class forces `Locale.US` as the default in order to assure other testcases use the correct format. However Spock seems to get in trouble. It looks to me that the value for `Locale.default` in the data table is cached before the base spec can change `Locale.default`.
