### ISSUE TITLE
Build Fails after lazybones templete creation

### ISSUE THREAD

**Issue by brazitech** [griffon/griffon#201]
After creating the project with lazybones (current version) the build fails.
 Error is at maven process-resources.xml line 9. It is looking for src/main/resources ,,, it should be src/main/izpack/resources. This happens on all templates. Needs to be changed to one or the other.

**Comment by aalmiray** [comment]
Could you paste the error details? Templates appear to work as expected when invoking  `mvn -Prun` as stated in the README.

**Comment by saviobosco** [comment]
@aalmiray  I get this error on build after lazybones template creation 

<code>:compileJava 
:compileGroovy SKIPPED
:processResources
:cssToBin SKIPPED
:classes
:run
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Griffon 2.10.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Build: 2017-03-02T16:39:27.094+0100
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Revision: 53c9e416aaf9650c0a16c0d573d2e6c9c52d8c31
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - JVM: 1.8.0_31 (Oracle Corporation 25.31-b07)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - OS: Linux 4.4.0-66-generic amd64
[griffon-pool-1-thread-1] INFO griffon.javafx.JavaFXGriffonApplication - Initializing all startup groups: [container]
[JavaFX Application Thread] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
java.lang.NoClassDefFoundError: javafx/scene/control/ButtonBar
        at griffon.javafx.support.JavaFXUtils.findElements(JavaFXUtils.java:1311)
        at griffon.javafx.support.JavaFXUtils.findElements(JavaFXUtils.java:1287)
        at griffon.javafx.support.ActionMatcher$1.match(ActionMatcher.java:49)
        at griffon.javafx.support.JavaFXUtils.connectActions(JavaFXUtils.java:587)
        at editor.ContainerView.init(ContainerView.java:59)
        at editor.ContainerView.initUI(ContainerView.java:42)
Caused by: java.lang.ClassNotFoundException: javafx.scene.control.ButtonBar
        ... 6 more
[griffon-pool-1-thread-1] WARN org.codehaus.griffon.runtime.core.view.AbstractWindowManager - Window at index 0 was not found

**Comment by saviobosco** [comment]
and this is my system specs

<code>java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by aalmiray** [comment]
`javafx.scene.control.ButtonBar` was added in Java8 update 40. Java8 update 60 is the recommended minimum version when using JavaFX, as there were many fixes plus a big missing feature (accessibility) added in that release. You appear to be using update 31. Please upgrade to the latest Java8 release (at this time it's update 131) if possible.

**Comment by saviobosco** [comment]
Ok Thanks I just updated my Java software and everything is good now.
