### ISSUE TITLE
Recommended / best-supported stack for greenfield project?

### ISSUE THREAD

**Issue by allquixotic** [griffon/griffon#239]
Various documentation sources seem to have different opinions of what the best-supported stack is for Griffon, in terms of widget toolkit and programming language. It seems this has changed a few times during Griffon's development.

Among Java vs. Groovy and Swing vs. JavaFX, is there any particular configuration that is particularly well-supported or poorly-supported today with Griffon? 

I'm working on a greenfield (new) project with no database component, just a simple config file and everything else is done involving some I/O workers and in-memory data structures. No SQL or other persistence mechanism besides the need for variable=value type config storage.

The project team I'm working with knows Java pretty well, and is encouraged to learn Groovy for the brevity it brings, but we've seen various things suggesting Groovy might not be the best supported with Griffon 2.x anymore. Is that true, or will we have a good experience either way?

Our current aim is to minimize code verbosity and maximize use of good design practices (MVC...) while strongly preferring DRY methodology. We like customizability in the GUI, but it does not need to be "pretty" -- it's more important that it's functional.

It would be nice to get a little bit of advice besides "use what you know" or "it depends". I like how the docs in various places put a star next to the "best supported" or "suggested" path forward, except that this seems to have changed over time, and an outsider can't necessarily tell what's the most up-to-date.

Also, we are pretty heavily married to Maven for a build system for many reasons. We can't go to Gradle right now (even though I personally prefer it). Will this hurt our ability to use Groovy or other features of Griffon at all?

**Comment by aalmiray** [comment]
That is true. Griffon's lineage can be traced to Grails; the first release of the framework was posted on September 10th 2008. At the time we concentrated our efforts in making Griffon a lightweight addition to what SwingBuilder offered. JavaFX was not in the radar at it was still very young and not ready for prime time as opposed to Swing. Groovy's dynamic features made it very easy for people to write applications with a concise syntax and a few lines of code.

JavaFX became a viable option as time passed by. Also, Griffon 2.x was revamped to support Java from the core, not just as an after thought. Ditto for JavaFX and Dependency Injection. This design goal enabled the framework to be more flexible in terms of language and UI toolkit choices. It can also target a broader audience as there's a sizable number of developers that prefer writing Java code rather than Groovy (or Kotlin). 

Many of the examples posted since 2.x came out showcase the usage of Java to entice and convince Java developers to give it a try. Seasoned Groovy developers know they can adapt the code using idiomatic Groovy based on their preferences. The official Griffon Guide continues to show Groovy code for brevity, opting for Java when it makes sense for a particular feature. The documentation of most Griffon plugins also show both Groovy and Java examples that can be C&P as a starting point.

My personal preference when writing Griffon applications is Groovy + JavaFX + Gradle, as witnessed by http://griffon-framework.org/whygriffon.html, specifically going with the "hybrid" approach when it comes to writing Views (explained at http://griffon-framework.org/tutorials/4_javafx_views.html) as I know GroovyFX may have some performance issues when building complex UIs. Relying on FXML makes it easier in my experience.

The choice of Gradle over Maven, for me comes mostly to the ability to adapt quickly to new requirements. However all Lazybones templates used to bootstrap Griffon projects also provide an starting maven setup. You can safely remove all gradle files from the project and continue to use maven. Using maven means there are additional steps to be configured as explained at http://griffon-framework.org/guide/2.11.0/#_buildtools_maven (the need for custom repositories is no longer true as now all artifacts are available from MC thanks to #237; the guide will be updated). There's no `maven-griffon-plugin` artifact at the moment, but one could be built in the future to supply feature parity with the gradle plugin if possible. Note that the gradle plugin does not perform a lot of magical steps behind the covers, rather it ensures conventions are followed and provides BOM resolution support, something that Gradle does not deliver out of the box but Maven does.

My recommendation for greenfield projects is to choose JavaFX as UI toolkit, as it has proved to be a good alternate choice to Swing. The usage of FXML and injection speeds things up. If the team is happy to go with Groovy then go ahead! Know that you can always fall back to Java or a Java-ish Groovy codebase, that's what I like about Groovy, you can fine tune how much idiomatic Groovy you use in your codebase, it's not an "all or nothing" proposition 😄. Regarding the build tool, Maven should work fine.

**Comment by allquixotic** [comment]
An extremely thoughtful and helpful response! It seems the Griffon devs (especially yourself) take great pride in the work you've produced, and have a thoughtful approach to the software development process. 

This answer was exactly what my team was looking for, so we will definitely take your suggestions into account. Thank you again!
