### ISSUE TITLE
Remove Lanterna support

### ISSUE THREAD

**Issue by aalmiray** [griffon/griffon#286]

**Comment by stigmelling** [comment]
Hi Andres. 
I'm using Griffon with Lanterna running an app on my Raspberry for scanning bar codes. 
Anything I can do to enable Lanterna on Griffon 3.0?

**Comment by aalmiray** [comment]
Oh hi! The reason to remove Lanterna from `3.x` is that I have not found (until today) an actual user for this feature 😄 

Lanterna `3.0.0` brings binary incompatibilities and thus I have not found the time to upgrade Griffon's support for it (see #250).

If Lanterna support remains then there are two options:

 1. Stay for a much longer time with Lanterna 2.x
 2. Bite the bullet and move to 3.x
 
Griffon `3.x` will bring binary incompatibilities of its own (as it will implement JSR-377) but will try to keep them to a minimum. Don't know yet how big the changes are from Lanterna's side thus your application might need to suffer a big refactoring session when upgrading to Griffon `3.x` if option 2 is taken and not so much if option 1 is the selected one. OTOH no more updates/bug fixes from Lanterna.

**Comment by stigmelling** [comment]
Thx for the update. Seems fair that you remove support for Lanterna ... and I try to enable it again :-)

**Comment by cognitivegears** [comment]
I hope you keep Lanterna support, and double down on it. I'm working on an open source project that has a diverse install base, from headless raspberry Pi's all the way to full blown mac and windows desktops. My dream is a framework where I can share the models and most of the presenters, and just change views where needed in order to get the same GUI to run in either text mode or as a full GUI. 

Griffon is the closest project I can see to that, the only thing missing is Lanterna 3 support for my direct needs.

And to go even further, adding Android / iOS support (looks like Basilisk is dead unfortunately) and native web support (GWT would work awesome here) would make for one heck of a framework where you could write an app that could run just about anywhere. Just an idea.

**Comment by aalmiray** [comment]
@cognitivegears I've resolved to keep Lanterna support in 3.x. This issue was created as there were no signs of people needing this feature in the past years. #250 tracks the upgrade to Lanterna 3.0.

Basilisk started as a fork of Griffon with the sole intention to target JavaFX, Java 8, and mobile. The use of the `java.beans` package is discouraged and prohibited in Android. Basilisk uses `openbeans` to get around this limitation. However Griffon 3.x will let go of `java.beans` completely which means it can target mobile too.

**Comment by cognitivegears** [comment]
This is fantastic. I'm going to work on integrating Griffon into our project then, and just wait for Griffon 3 for Lanterna 3 support (need the file dialog among other things.) Thanks!

**Comment by aalmiray** [comment]
Both Lanterna `2.x` and `3.x` will be supported in Griffon `3.x`.

**Comment by aalmiray** [comment]
Closing this issue. Lanterna support remains.
