### ISSUE TITLE
On Windows, with JavaFX and FXML files, fxml not found when running from JAR files

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#310]
My Application name is RrTools. It runs fine from Gradle Run, but building a shadow jar or jar file, the run fails with unable to load resource name "rrTools.fxml".  The class name is RrToolsView, the "name" is "RrTools", the "naturalName is "RrToolsView", the "shortName" is "RrToolsView", but the "logicalPropertyName" is "rrTools" The GriffonNameUtils class has lower-cased the property name, now the fxml needs to be renamed from RrTools.fxml to "rrTools.fxml". The load succeeds when running from Gradle run (at least on Windows), but fails when attempting to load from a Jar file.

I suspect this is a Windows behavior and I'm not quite sure what the correct resolution is - should the original filebe named"rrTools.fxml", or should GriffonNameUtils not be lower-casing the begining of the name, or should "resolveBasename() in AbstractFXGriffonView be using a different property?

**Comment by aalmiray** [comment]
Yes, that's the expected behavior. `logicalPropertyName(viewClass) + '.fxml'` as witnessed by

https://github.com/griffon/griffon/blob/development/subprojects/griffon-javafx/src/main/java/org/codehaus/griffon/runtime/javafx/artifact/AbstractJavaFXGriffonView.java#L61-L63

https://github.com/griffon/griffon/blob/development/subprojects/griffon-javafx/src/main/java/org/codehaus/griffon/runtime/javafx/artifact/AbstractJavaFXGriffonView.java#L113-L121

It's been like that since day 1, which means your application should had used `rrTools.fxml` from the start. It appears that's not the case and Windows' case insensitive filesystem is getting in the way. Fortunately there's an alternative, use the other variant of `loadFromFXML()` that takes a given basename

https://github.com/griffon/griffon/blob/development/subprojects/griffon-javafx/src/main/java/org/codehaus/griffon/runtime/javafx/artifact/AbstractJavaFXGriffonView.java#L66-L98

```java
loadFromFXM("RrTools");
```

Bear in mind this requires the following resources to exist:

* RrTools.fxml
* RrTools.css

**Comment by swalton00** [comment]
I can live with that. But where is that documented, especially that only the first TWO characters are lower-cased, and that the fxml name uses that form? I'll close this as soon as I figure out how I would know that from the beginning, when I created the fxml.

**Comment by aalmiray** [comment]
It's only the first character, not the first two.

It appears the convention is not explicitly documented however all examples in the guide (with the exception of MetaComponent,`form.xml` shoud had been `formItem.fxml`instead) do follow the convention. Event the tutorials show the convention in place

http://griffon-framework.org/tutorials/3_mvcgroups_javafx.html
http://griffon-framework.org/tutorials/4_javafx_views.html#_tutorial_4_4

Also, projects created with the Maven archetype or the Layzbones template will make use of the convention.

**Comment by swalton00** [comment]
Yes, I see all of those, and agree. Windows gets me again! I did a little testing and, if the first TWO characters are both caps, they are left alone! So I'll go ahead and close this now -- I'm able to run with distZip and shadowJar, so I have a way to distribute the app.

**Comment by swalton00** [comment]
It's interesting that, though the doc says "baseName:", loadFromFXML actually requires the fully qualified name.
