### ISSUE TITLE
having problems with setup and laybones template build incomplete for swing and javafx

### ISSUE THREAD

**Issue by woodmawa** [griffon/griffon#55]
i'm trying to run under windows - cnat get gvm working in side Cygwin - so installed laybones0.8 on local machine by hand.  create new workspace for eclipse, and create project using griffon-swing-groovy and griffon-javafx-groovy 

I edit the build.gradle by hand to add plugin eclipse (or idea) as they are not there.

run the build task and import the project into ide.

run you try and run either of the two projects via launcher - both fail.  in case of swing project its because the generated view doesn't include the actions referenced in the button - the template should be com0plete and run 

in the case of the java fx example has same problem - actions aren't defined in the view - but before you get to that its says it cant read from null context - somehow the context is not being built and when you get the config it fails on builder.application(title: application.configuration['application.title'], saying configuration is null 

all I did was set my own package in the lazybones install script (set to org.softwood) rather than except default 

net is that there are to errors.  I can hack the swing one to work (add actions) but cant hack the javafx.

this should all work ok and templates you be fully consistent and work 

if I had a suggestion i'd try and use grails itself to control all this.  If you look at grails3 your install grails 3 cli - and create-app (akin to your lazybones) but build .gradle has everything needed to build including eclipse and idea plugins.  all I have to do is import into IDE and inform ide its a gradle project and it all works 

griffon feels clunkier - theres griffon cli/shell equiv and the templates didn't generate working code 

for newbies (including me) this a little frustrating hope we canm fix some of this before version 2 ships

regards Will

**Comment by aalmiray** [comment]
Hi Wil,

I think the `idea` plugin is added by default when the `griffon` plugin is applied. See https://github.com/griffon/griffon/blob/development/subprojects/gradle-griffon-plugin/src/main/groovy/org/codehaus/griffon/gradle/GriffonPlugin.groovy#L72 The `eclipse` plugin could also be added in this way.
More information on what the `griffon` plugin does for you can be found at http://new.griffon-framework.org/guide/latest/index.html#_the_griffon_plugin

Both templates you mention work perfectly well on OSX and Linux. On Windows, well, this OS is well known for its inability to properly handle even the most basic functions. We've had reports that moving/deleting files have caused trouble, and perhaps that's what's happening here. I thought we had squashed the bug back in release 1.1.0 of the templates, apparently there's still some problem. Could you please create a brand new application with both templates and post a detailed file structure? Cygwin should be able to give you access to an utility named `tree`. Or take a screenshot of an explorer window if it does not. This is how we can tell if the templates have created the expected files and the right locations or if there's something missing. Do you get any warnings stating that some files couldn't be moved/deleted at all?

Could you also post stacktraces of each run?

Regarding the command found in Grails 3. We thought on doing something similar but then again that limits our options a bit. You see, Grails 3 works with Gradle (which is awesome!) and nothing more. In the past we've had users asking for Maven support. In hindsight it was silly to create our own build tool on top of Gant (another build tool) that emulated Gradle. This is what Grails 1, 2 and Griffon 1 did.

Now we rely on the native build tool of your choosing. This is why there's no specific griffon command anymore, and there won't be any in the foreseeable future. Gradle does not have a facility similar to archetypes like Maven does. If Gradle adds it you can be sure we'll use it. In the meantime we use Lazybones because it does not make sense to build a competing tool. There's a group working on a Forge addon that will make working with Maven and Griffon a breeze.

Version 2 has shipped already (back in Sep 2014). That's the version you're trying right now. We're on version 2.2.0 at the moment.

**Comment by woodmawa** [comment]
andre  - sent some stuff over I hope on your email - however I think part of the problem is because the configuration policy - 

so in the views you generate with lazybones - you use a button with action : 'clickAction'  but no actions are defined in the view at all - I think whats happening is that when you run the project the view processing is removing the Action in 'clickAction' and looking for a controller action called 'click()'  which is there.  

so it sorts of works when you gradle run the app - but the eclipse build cant understand what the framework is doing round the back.  

need to try again - one for idea and one for eclipse.  

an idea task is implicitly added by the gradle.build but an eclipse task is not - I have to edit that in myself to generate the eclipse project files

**Comment by aalmiray** [comment]
Hi William,
Indeed, what you just described is what's actually happening due to the conventions of the Griffon actions, controllers and views. This is the expected behavior.IntelliJ will mark the missing variable (clickAction) with an underline but would not issue a warning nor compilation error. It looks like Eclipse's Groovy editor is stricter if it underlines with red the missing variable. The editor should be lenient enough as the clickAction variable will eventually be available as part of the builder's variables.

I may be mistaken but the idea plugin is lighter than the eclipse plugin, thus applying the idea plugin in build.gradle by default is almost a noop whereas applying the eclipse plugin is not. Have to check that out again.
Cheers,Andres -------------------------------------------
Java Champion, Groovy Enthusiast
http://jroller.com/aalmiray
http://www.linkedin.com/in/aalmiray
--
What goes up, must come down. Ask any system administrator.
There are 10 types of people in the world: Those who understand binary, and those who don't.
To understand recursion, we must first understand recursion. 


     On Wednesday, April 8, 2015 3:04 PM, woodmawa <notifications@github.com> wrote:
   

 andre - sent some stuff over I hope on your email - however I think part of the problem is because the configuration policy - so in the views you generate with lazybones - you use a button with action : 'clickAction' but no actions are defined in the view at all - I think whats happening is that when you run the project the view processing is removing the Action in 'clickAction' and looking for a controller action called 'click()' which is there. so it sorts of works when you gradle run the app - but the eclipse build cant understand what the framework is doing round the back. need to try again - one for idea and one for eclipse. an idea task is implicitly added by the gradle.build but an eclipse task is not - I have to edit that in myself to generate the eclipse project files —

**Comment by woodmawa** [comment]
sorry this is a bit sporadic - but my 'normal' job doesn't leave a lot of time to explore

i tried again - both with eclipse and idea and used gradle in both after importing into both IDE 

so for eclipse - i used lazybones and created a default a new eclipseSwingApp in a workspace.
I chnage directory into that and run i edit the gradle.build to add the eclipse plugin.  
i then run gradle eclipse task, and gradle build tasks so far so good 

I take a freshly minted eclipse luna build, into which i have installed groovy eclipse and gradle plugins for eclipse.

I then import the eclipseSwingApp  into the builder as eclipse project , - let it settle a mo - and then convert to gradle using the right click >convert > gradle project.  let it all settle.  

in eclipse add the gradle 'view' and select your eclipseSwingApp and it shows you the gradle.build targets.  

you can select the gradle run task and the app will run window appears and you can click etc on the button.  

eclipse isnt showing any errors at this point - so what i tried to do is go to source>main>groovy and select the launcher.groovy file and then right click on the file and do runAs> Java Application 

i get an error like this 

[2015-04-19 13:34:11,380] [main] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Build: 2015-03-01T12:26:04.727+0100
[2015-04-19 13:34:11,380] [main] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - JVM: 1.8.0_31 (Oracle Corporation 25.31-b07)
[2015-04-19 13:34:11,380] [main] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - OS: Windows 8.1 6.3 amd64
[2015-04-19 13:34:11,978] [main] INFO  griffon.swing.SwingGriffonApplication - Initializing all startup groups: [eclipseSwingApp]
[2015-04-19 13:34:12,533] [main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
groovy.lang.MissingPropertyException: No such property: clickAction for class: griffon.util.CompositeBuilder
	at griffon.util.CompositeBuilder$2.doCall(CompositeBuilder.java:116)
	at org.softwood.EclipseSwingAppView$_initUI_closure1$_closure2.doCall(EclipseSwingAppView.groovy:23)
	at org.softwood.EclipseSwingAppView$_initUI_closure1$_closure2.doCall(EclipseSwingAppView.groovy)
	at org.softwood.EclipseSwingAppView$_initUI_closure1.doCall(EclipseSwingAppView.groovy:19)
	at org.softwood.EclipseSwingAppView.initUI(EclipseSwingAppView.groovy:13)

This is where i was confused at first.  In the griffon framework if you add a 'void click ()' method - the action handler will expose that to the view as a clickAction for the button to use which is what the lazybones templates create.  

i don't understand why a direct run on launcher fails - but gradle run task works.  Something in how the environment is started ?

so what happened in idea.  Created another demo app in same workspace called newSwingApp (inconsistent naming down to weeks gap or so)

I then just imported this a a gradle project into eclipse 4.1 (i've gone to same version as on my work laptop - till i figure out whats different in any of the tooling ) 

if you try and open the gradle view and build the project - it reported an issue with missing log4j stuff so i added one extra line to the build.gradle - thats not in the lazybones template 

    runtime 'org.slf4j:slf4j-api:1.7.12'

and rebuilt - it all happy

i can do the gradle run task - up comes the window i can use the app (just as i can from eclipse gradle.


now in idea i go into the project explorer again and select the launcher.groovy file and try and run it 

- first of all it was giving me errors about groovyClass etc - bit weird so i went back to view and hit the refresh-all in the top left of the gradle view screen.

it did some stuff so i re tried running the launcher.groovy 

this doest even get to running the framework - eclipse got so far as trying and then it failed some way through the initialisation.  Idea dies earlier i think, saying it cant find     org/codehaus/griffon/runtime/core/AbstractGriffonApplication.  

i look in the external libraries in the project explorer and its definitely there 

"C:\Program Files\Java\jdk1.8.0_40\bin\java" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\bin" -Dfile.encoding=windows-1252 -classpath "C:\Program Files\Java\jdk1.8.0_40\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\zipfs.jar;E:\workspace-griffon\newSwingApp\build\classes\main;E:\workspace-griffon\newSwingApp\build\resources\main;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.codehaus.griffon\griffon-guice\2.2.0\bdcf3fb23721dd252ea80a9dec7ee4bbacce7794\griffon-guice-2.2.0.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.codehaus.griffon\griffon-swing\2.2.0\20de0c0ef5c327d37e7caf97556dc44ea379275f\griffon-swing-2.2.0.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.codehaus.griffon\griffon-swing-groovy\2.2.0\4d359a092dec38f9aacb3fab8467a2a2520d10ca\griffon-swing-groovy-2.2.0.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\com.google.inject\guice\3.0\9d84f15fe35e2c716a02979fb62f50a29f38aefa\guice-3.0.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\aopalliance\aopalliance\1.0\235ba8b489512805ac13a8f9ea77a1ca5ebe3e8\aopalliance-1.0.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\log4j\log4j\1.2.17\5af35056b4d257e4b64b9e8069c0746e8b08629f\log4j-1.2.17.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.codehaus.groovy\groovy-all\2.4.3\472f5124c90a551d7ac7ffa39a4a3ba36ac4586a\groovy-all-2.4.3.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.12\8e20852d05222dc286bf1c71d78d0531e177c317\slf4j-api-1.7.12.jar;E:\gradle\gradleUserHome\caches\modules-2\files-2.1\org.slf4j\slf4j-log4j12\1.7.12\485f77901840cf4e8bf852f2abb9b723eb8ec29\slf4j-log4j12-1.7.12.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.softwood.Launcher
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/griffon/runtime/core/AbstractGriffonApplication
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.softwood.Launcher.main(Launcher.groovy:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.codehaus.griffon.runtime.core.AbstractGriffonApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

Process finished with exit code 1

so what i have is two apps - once for eclipse which i had to add the eclipse task and it cant run the launcher directly , and the same for idea but find abstractGriffonClass

both 'work' and run if in stick to gradle only as the means to run the apps 

any ideas?

the eclipse one is worrying as it cant seem to identify the clickAction - which suggests something serious is being missed in the startup the framework and the dynamic code matching alickAction -> controller.click() isn't happening 

frustrating in both cases - not quite sure what next step to resolve either issues are - but i'm either doing something stupid (entirely probable ) or something starts weirdley when you do a run action from either IDE

**Comment by RogerPf** [comment]
I confirm this is also happens with Eclipse under Linux (Mint 17.1) - so this is NOT a windows issue.

In summary (since griffon 2) it is not possible to debug Griffon apps under Eclipse.   Yes you can use Layzbones to create the app frame work and Gradle to run it (even within Eclipse) BUT  if you want breakpoints ! you have to (I assume) go and buy  IntelliJ IDEA Ultimate.

Unless someone knows otherwise.

**Comment by aalmiray** [comment]
I'll have a look again at Eclipse integration. AFAIK this is a groovy/greclipse problem due to the inherent limitations of the Eclipse platform itself. 

You don't have to buy a license for IDEA Ultimate, the community Edition (free and open source too) works just as well. You can try NetBeans too, also free and open source, even comes with OSGi support.

**Comment by RogerPf** [comment]
> You don't have to buy a license for IDEA Ultimate, the community Edition (free and open source too) works just as well. 

Oh that is interesting - their documentation says that for Griffon you need the Ultimate edition but from your comment I assume that that was is a Griffon 1.5 thing  and it all might just all work as a Gradle project.     Thanks

**Comment by aalmiray** [comment]
I've finally figured out what's the problem with Eclipse: annotation processors are not enabled by default on Eclipse. you must turn on the feature per project, as explained at http://stackoverflow.com/questions/9850952/eclipse-java-annotation-processing

Enabling the APT is not enough, you must specify all jars containing processors too. You can achieve this by specifying the factorypath.

IntelliJ only requires you to enable APT. JARs will be discovered from the classpath automatically.
NetBeans picks up APT processors automatically, there's no need to manually enable APT processing.

I'll leave this ticket open to keep track of documentation changes

**Comment by akardapolov** [comment]
Have the same error while running any launcher from samples directory.

Stack trace when running browser-javafx-groovy sample here;

Exception in thread "main" java.lang.NoClassDefFoundError: griffon/core/GriffonApplication
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at browser.Launcher.main(Launcher.groovy:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: griffon.core.GriffonApplication
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more

- IDE - IntelliJ 14, 15
- Griffon 2.4.0
- Annotation Processing enabled
![image](https://cloud.githubusercontent.com/assets/537977/12604887/674a30e0-c4e1-11e5-849d-a5f4b03529e5.png)

Thanks,
Alex.

**Comment by aalmiray** [comment]
this is a separate issue. You can't run the samples available at the griffon/griffon repository directly from the IDE. You must run them using the command line for the time being.
